version: '3'

networks:
  app:
    driver: bridge

services:

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    networks:
      - app
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    networks:
      - app
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT="zookeeper:2181"
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - '9093:9092'

  microtest:
    networks:
      - app
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - '8081:8081'
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
    depends_on:
      - kafka

